// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=js+dts"
// @generated from file payment.proto (package payment.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetTransactionRequest, PaymentResult, ProcessPaymentRequest, Transaction } from "./payment_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service payment.v1.PaymentService
 */
export const PaymentService = {
    typeName: "payment.v1.PaymentService",
    methods: {
        /**
         * @generated from rpc payment.v1.PaymentService.ProcessPayment
         */
        processPayment: {
            name: "ProcessPayment",
            I: ProcessPaymentRequest,
            O: PaymentResult,
            kind: MethodKind.Unary,
        },
        /**
         * @generated from rpc payment.v1.PaymentService.GetTransaction
         */
        getTransaction: {
            name: "GetTransaction",
            I: GetTransactionRequest,
            O: Transaction,
            kind: MethodKind.Unary,
        },
    },
};
