// @generated by protoc-gen-es v1.7.2 with parameter "target=js+dts"
// @generated from file payment.proto (package payment.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message payment.v1.ProcessPaymentRequest
 */
export const ProcessPaymentRequest = proto3.makeMessageType(
    "payment.v1.ProcessPaymentRequest",
    () => [
        { no: 1, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "amount", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
        { no: 3, name: "currency", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ],
);

/**
 * @generated from message payment.v1.PaymentResult
 */
export const PaymentResult = proto3.makeMessageType(
    "payment.v1.PaymentResult",
    () => [
        { no: 1, name: "success", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
        { no: 2, name: "transaction_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ],
);

/**
 * @generated from message payment.v1.GetTransactionRequest
 */
export const GetTransactionRequest = proto3.makeMessageType(
    "payment.v1.GetTransactionRequest",
    () => [
        { no: 1, name: "transaction_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ],
);

/**
 * @generated from message payment.v1.Transaction
 */
export const Transaction = proto3.makeMessageType(
    "payment.v1.Transaction",
    () => [
        { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "user_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 3, name: "amount", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
        { no: 4, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ],
);
