// @generated by protoc-gen-es v1.7.2 with parameter "target=js+dts"
// @generated from file user.proto (package user.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message user.v1.GetUserRequest
 */
export const GetUserRequest = proto3.makeMessageType(
    "user.v1.GetUserRequest",
    () => [
        { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ],
);

/**
 * @generated from message user.v1.CreateUserRequest
 */
export const CreateUserRequest = proto3.makeMessageType(
    "user.v1.CreateUserRequest",
    () => [
        { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ],
);

/**
 * @generated from message user.v1.User
 */
export const User = proto3.makeMessageType(
    "user.v1.User",
    () => [
        { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 3, name: "email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    ],
);
