// @generated by protoc-gen-connect-es v1.3.0 with parameter "target=js+dts"
// @generated from file user.proto (package user.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateUserRequest, GetUserRequest, User } from "./user_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service user.v1.UserService
 */
export const UserService = {
    typeName: "user.v1.UserService",
    methods: {
        /**
         * @generated from rpc user.v1.UserService.GetUser
         */
        getUser: {
            name: "GetUser",
            I: GetUserRequest,
            O: User,
            kind: MethodKind.Unary,
        },
        /**
         * @generated from rpc user.v1.UserService.CreateUser
         */
        createUser: {
            name: "CreateUser",
            I: CreateUserRequest,
            O: User,
            kind: MethodKind.Unary,
        },
    },
};
